CFLAGS = -std=c11 -Wall -Wextra -Wstrict-prototypes -Wredundant-decls -Wshadow -pedantic -pedantic -fno-strict-aliasing -D_XOPEN_SOURCE=700 -O2 -I./
LDFLAGS = 
BIN = matmult-oacc
OPENACC_FLAGS = -fopenacc -foffload=amdgcn-amdhsa="-march=gfx900"

all: $(BIN)
	
matmult-oacc: matmult-oacc.c
	$(CC) $(CFLAGS) $(OPENACC_FLAGS) -o $@ $? $(LDFLAGS)

clean:
	rm -f $(BIN)
	rm -f *.o 

